name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1

  # Core Utilities
  dio: ^5.7.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

  # Routing
  auto_route: ^9.2.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  auto_route_generator: ^9.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
