name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Core Utilities
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  flutter_gen: ^5.8.0
  easy_localization: ^3.0.7
  app_tracking_transparency: ^2.0.6
  recase: ^4.1.0
  envied: ^0.5.4+1

  # State Management
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1

  # Network
  dio: ^5.7.0

  # Cache
  path_provider: ^2.1.5
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  # Image
  image: ^4.3.0
  flutter_svg: ^2.0.12

  # Device
  permission_handler: ^11.3.1
  image_picker: ^1.1.2

  # UI
  gap: ^3.0.1
  auto_size_text: ^3.0.0

  # Routing
  auto_route: ^9.2.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  hive_generator: ^2.0.1
  envied_generator: ^0.5.4+1
  auto_route_generator: ^9.0.0
  mocktail: ^1.0.4

flutter_gen:
  output: lib/core/gen
  integrations:
    flutter_svg: true
    lottie: true
  colors:
    inputs:
      - assets/styles/colors.xml
    outputs:
      class_name: ArteriaColors

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/styles/
    - assets/translations/
